languageCode: "en-us"
title: "Protect Tasmania"
theme: "microsite-template"
server:
  _merge: deep
markup:
  goldmark:
    renderer:
      unsafe: true
services:
  # https://gohugo.io/templates/embedded/#configuration-google-analytics
  # googleAnalytics:
  #   id: G-MEASUREMENT_ID
menus:
  main:
    - name: About
      pageRef: https://protecttasmania.org/
      weight: 10
# Avoid camel casing params. Hugo downcases all params when it parses the config.
# We can still case-insensitively access params, but if we try to dump them as a json blob
# we will lose the camel casing which can be confusing later.
params:
  api_host: https://api.ecosounds.org
  workbench_host: https://api.ecosounds.org
  hero_image: images/fortyspotted_wide.jpg
  navbar:
    logo:
      image: "images/protect_tasmania.png" # default: none
      text: "Tassie Calling" # default: {{ .site.Title }}
  # sponsors:
  #   logos:
  #     - image: "images/OpenEcoacoustics_horizontal_rgb.svg"
  #       alt: "Open Ecoacoustics Logo"
  #       url: "https://stakeholder.org/"
  tasks:
    verification: true # default: true
  campaigns:
    - name: "Forty-spotted Pardalote"
      filters:
        filter:
          tags.id:
            eq: 3031 # Forty-spotted Pardalote
          projects.id:
            eq: 1178


  style:
    roundedButtons: true
    # Theme colors are defined using "hsl" (hue, saturation, lightness).
    # To create your own hsl theme color, you can use the following website.
    # https://hslpicker.com/#ca7d2f
    themeColor:
      hue: 19deg
      saturation: 97.1%
      lightness: 59.6%
    themeShades:
      "50": hsl(from hsl(19deg 97.1 59.6) h s calc(l + 0.62))
      "100": hsl(from hsl(19deg 97.1 59.6) h s calc(l + 0.52))
      "200": hsl(from hsl(19deg 97.1 59.6) h s calc(l + 0.40))
      "300": hsl(from hsl(19deg 97.1 59.6) h s calc(l + 0.28))
      "400": hsl(from hsl(19deg 97.1 59.6) h s calc(l + 0.14))
      "500": hsl(from hsl(19deg 97.1 59.6) h s calc(l + 0.00))
      "600": hsl(from hsl(19deg 97.1 59.6) h s calc(l - 0.08))
      "700": hsl(from hsl(19deg 97.1 59.6) h s calc(l - 0.14))
      "800": hsl(from hsl(19deg 97.1 59.6) h s calc(l - 0.20))
      "900": hsl(from hsl(19deg 97.1 59.6) h s calc(l - 0.26))
      "950": hsl(from hsl(19deg 97.1 59.6) h s calc(l - 0.32))
